name: Daily Docker Cycle (09:30 PM IST)

on:
  schedule:
    # 16:00 UTC = 21:30 IST
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  docker-cycle:
    runs-on: ubuntu-latest
    timeout-minutes: 290
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Make script executable
        run: chmod +x script.sh

      - name: Run cyclic Docker script
        run: ./script.sh
